#!/bin/bash

# echo "--| params: $@"

case $1 in
  "")
    ;;
  "install")
    shift 1

    react_install $*
    ;;
  "component")
    shift 1

    react_component $*
    ;;
  "uninstall")
    react_uninstall
    ;;
esac
