#!/usr/local/bin/bash

dirProject=""

echo "--| command: react install"

# ---| Validate command options
while getopts ":n:" o;
do
  case $o in
    n)
      # echo " -| option '$o' = ${OPTARG}"
      dirProject=$OPTARG
      ;;
    :)
      # echo " -| option '$o' has no value"
      ;;
  esac
done

# ---| Perform installation
if test $dirProject
then
  echo " -| clone repo to: $dirProject"

  git clone -q https://github.com/willfull-git/react-base $dirProject && cd $dirProject
  touch .react-cli
  touch .react-cli-log
  
  . react_anim
  echo " -| install npm packages"
  npm i --silent > .react-cli-log

  echo " -| done"
else
  echo " -| operation failed"
fi
