#!/bin/bash

# state
command=''

echo "--| params: $@"

case $1 in
  "")
    ;;
  "install")
    shift 1

    react_install $*
    ;;
  "component")
    shift 1

    react_component $*
    ;;
  "uninstall")
    # echo "you have choosed 'uninstall' command"
    react_uninstall
    ;;
esac
