#!/bin/bash

$dir=""

echo "--| command: react install"
echo " -| options ${*}"

# ---| Validate command options
while getopts ":n:" o;
do
  case $o in
    n)
      echo " -| option '$o' = ${OPTARG}"
      dir=$OPTARG
      ;;
    :)
      echo " -| option '$o' has no value"
      ;;
  esac
done

echo " -| dir: ${dir}"

# ---| Perform installation
if test $dir
then
  echo " -| clone repo to: $dir"

  git clone -q https://github.com/willfull-git/react-base $dir && cd $dir
  mkdir $dir && cd ./$dir

  npm i
  echo " -| install npm packages"

  echo " -| done"
else
  echo " -| operation discard"
fi
